"""New Setup

Revision ID: 2e1b820b6522
Revises: 
Create Date: 2020-09-08 18:05:40.935975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1b820b6522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry_long',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=False),
    sa.Column('number_of_staff', sa.String(length=5), nullable=True),
    sa.Column('move_date', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('comments', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_long_company_name'), 'enquiry_long', ['company_name'], unique=False)
    op.create_index(op.f('ix_enquiry_long_email'), 'enquiry_long', ['email'], unique=False)
    op.create_index(op.f('ix_enquiry_long_name'), 'enquiry_long', ['name'], unique=False)
    op.create_table('enquiry_short',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_short_email'), 'enquiry_short', ['email'], unique=False)
    op.create_index(op.f('ix_enquiry_short_name'), 'enquiry_short', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('editor', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_enquiry_short_name'), table_name='enquiry_short')
    op.drop_index(op.f('ix_enquiry_short_email'), table_name='enquiry_short')
    op.drop_table('enquiry_short')
    op.drop_index(op.f('ix_enquiry_long_name'), table_name='enquiry_long')
    op.drop_index(op.f('ix_enquiry_long_email'), table_name='enquiry_long')
    op.drop_index(op.f('ix_enquiry_long_company_name'), table_name='enquiry_long')
    op.drop_table('enquiry_long')
    # ### end Alembic commands ###
